### ISSUE TITLE
Lights are glitched out on ARM based Mac

### ISSUE THREAD

**Issue by UrkiMimi** [AllPoland/ArcViewer#37]
**Describe the bug**

**To Reproduce**
1. Open any replay on any ARM based Mac.
2. Profit. May be more noticeable when you have lights set to static.

**Expected behavior**
Lights will glitch out and have rendering issues.
<img width="358" alt="Screenshot 2023-08-27 at 11 31 21 PM" src="https://github.com/AllPoland/ArcViewer/assets/74517821/0b49838a-a90d-4637-b9af-74c11edfb72f">

**Build Info:**
 - Platform: macOS 14 DP6, Firefox 116 Universal
 - Version v0.5.2

**Comment by AllPoland** [comment]
I can't really tell what's wrong based on that image, could you possibly record a video of the lights glitching out?

**Comment by UrkiMimi** [comment]
https://github.com/AllPoland/ArcViewer/assets/74517821/dc377c69-aad9-4c60-8092-228c5024de9c

What I've also discovered is that opening ArcViewer in the Unity Editor seems to sort of fix this issue as they don't flicker when the camera is moved.

**Comment by AllPoland** [comment]
Looks like Z fighting, fairly easy fix 👍🏻

Though it's kind of odd that it's only happening on some platforms

**Comment by AllPoland** [comment]
Should be fixed in 0.5.3

**Comment by UrkiMimi** [comment]
I'm still getting the issue on v0.5.3. [Apparently, this is an issue with Unity WebGL itself not liking the Metal API on ARM and not the viewer.](https://forum.unity.com/threads/webgl-build-of-urp-project-not-rendering-properly-in-chrome-safari-on-mac-and-ios.1432639/)
<img width="401" alt="Screen Shot 2023-08-28 at 6 42 02 PM" src="https://github.com/AllPoland/ArcViewer/assets/74517821/995aa72d-87fc-4615-9b1f-e5704982a19d">

**Comment by AllPoland** [comment]
Actually, that's still just Z fighting, I forgot to bump the scale of that right-hand laser lmao
Should be fixed whenever I push the next update.

**Comment by AllPoland** [comment]
Ok, decided to just push a hotfix with a couple other things anyway. It *should* be fixed now, but definitely do tell me if it still happens somewhere.
